-- Auto-generated face layout (ti-keypad-layout v2).
-- Edit with Love2D Panel Editor or by hand. Readable by ComputerCraft.
return {
  format = "ti-keypad-layout",
  version = 2,
  machine = "ti89",
  design_cols = 5.0000,
  design_rows = 11.3500,
  face_aspect = 1.6200,
  scene = { w=5.0000, h=14.6750 },
  lcd = {
    x=0.2000, y=0.5000, w=4.6500, h=2.9063, radius=0.2100,
    color = { 0.0800, 0.0800, 0.0900 },
    glass = { 0.1200, 0.1400, 0.1200 },
  },
  panel = {
    x=0.0000, y=3.3250, w=5.0000, h=11.3500, radius=0.0600,
  },
  plate = {
    body = { 0.2400, 0.2600, 0.2800 },
    fkey_band = { 0.1500, 0.1600, 0.1700 },
    fkey_band_end = 1.1400,
    radius = 0.0600,
  },
  theme = {
    styles = {
      ["alpha"] = { 0.9300, 0.9300, 0.9500 },
      ["arrow"] = { 0.1700, 0.1800, 0.1900 },
      ["diamond"] = { 0.6200, 0.9200, 0.3800 },
      ["enter"] = { 0.1700, 0.1800, 0.1900 },
      ["fkey"] = { 0.1700, 0.1800, 0.1900 },
      ["fn"] = { 0.1700, 0.1800, 0.1900 },
      ["num"] = { 0.3800, 0.4000, 0.4200 },
      ["on"] = { 0.1700, 0.1800, 0.1900 },
      ["second"] = { 0.4500, 0.7200, 0.9500 },
      ["shift"] = { 0.4200, 0.4400, 0.4600 },
    },
    label_size = 12,
    legend_size = 9,
    legend_2nd = { 0.5500, 0.7800, 0.9800 },
    legend_alpha = { 0.9500, 0.9500, 0.9700 },
    legend_shift = { 0.7200, 0.9500, 0.4500 },
    legend_fkey = { 0.5500, 0.7800, 0.9800 },
    press = { 0.9000, 0.4800, 0.1200 },
  },
  buttons = {
    { id="f1", label="F1", style="fkey", x=0.0500, y=0.3500, w=0.9000, h=0.9400, second="F6", alpha=nil, shift="Y=", fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=4, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="f2", label="F2", style="fkey", x=1.0500, y=0.3500, w=0.9000, h=0.9400, second="F7", alpha=nil, shift="WINDOW", fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=4, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="f3", label="F3", style="fkey", x=2.0500, y=0.3500, w=0.9000, h=0.9400, second="F8", alpha=nil, shift="GRAPH", fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=4, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="f4", label="F4", style="fkey", x=3.0500, y=0.3500, w=0.9000, h=0.9400, second=nil, alpha=nil, shift="TblSet", fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=4, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="f5", label="F5", style="fkey", x=4.0500, y=0.3500, w=0.9000, h=0.9400, second=nil, alpha=nil, shift="TABLE", fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=4, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="up", label="up", style="arrow", x=3.6500, y=1.5000, w=0.7000, h=0.8100, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=9, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="left", label="left", style="arrow", x=3.2000, y=2.1000, w=0.7500, h=0.8400, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=9, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="right", label="right", style="arrow", x=4.1000, y=2.1000, w=0.7000, h=0.8400, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=9, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="down", label="down", style="arrow", x=3.6500, y=2.7500, w=0.7500, h=0.8400, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.1200, color=nil, label_color=nil, label_size=12, legend_size=9, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="2nd", label="2nd", style="second", x=0.0000, y=1.8500, w=1.0000, h=1.0000, second=nil, alpha=nil, shift="CUT", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="shift", label="shift", style="shift", x=1.0000, y=1.8500, w=1.0000, h=1.0000, second=nil, alpha=nil, shift="COPY", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="esc", label="ESC", style="fn", x=2.0000, y=1.8500, w=1.0000, h=1.0000, second="QUIT", alpha=nil, shift="PASTE", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="diamond", label="diamond", style="diamond", x=0.0000, y=2.9000, w=1.0000, h=1.0000, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="alpha", label="ALPHA", style="alpha", x=1.0000, y=2.9000, w=1.0000, h=1.0000, second="a-lock", alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="apps", label="APPS", style="fn", x=2.0000, y=2.9000, w=1.0000, h=1.0000, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="home", label="HOME", style="fn", x=0.0000, y=3.9500, w=1.0000, h=1.0000, second="CUSTOM", alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="mode", label="MODE", style="fn", x=1.0000, y=3.9500, w=1.0000, h=1.0000, second="switch", alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="catalog", label="CATALOG", style="fn", x=2.0000, y=3.9500, w=1.0000, h=1.0000, second="inf_i", alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="backspace", label="bs", style="fn", x=3.0000, y=3.9500, w=1.0000, h=1.0000, second="INS", alpha=nil, shift="DEL", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="clear", label="CLEAR", style="fn", x=4.0000, y=3.9500, w=1.0000, h=1.0000, second=nil, alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="x", label="X", style="fn", x=0.0000, y=5.0000, w=1.0000, h=1.0000, second="LN", alpha=nil, shift="e^x", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="y", label="Y", style="fn", x=1.0000, y=5.0000, w=1.0000, h=1.0000, second="SIN", alpha=nil, shift="SIN-1", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="z", label="Z", style="fn", x=2.0000, y=5.0000, w=1.0000, h=1.0000, second="COS", alpha=nil, shift="COS-1", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="t", label="T", style="fn", x=3.0000, y=5.0000, w=1.0000, h=1.0000, second="TAN", alpha=nil, shift="TAN-1", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="power", label="^", style="fn", x=4.0000, y=5.0000, w=1.0000, h=1.0000, second="pi", alpha=nil, shift="theta", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="equals", label="=", style="fn", x=0.0000, y=6.0500, w=1.0000, h=1.0000, second="#", alpha="a", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="lparen", label="(", style="fn", x=1.0000, y=6.0500, w=1.0000, h=1.0000, second="{", alpha="b", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="rparen", label=")", style="fn", x=2.0000, y=6.0500, w=1.0000, h=1.0000, second="}", alpha="c", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="comma", label=",", style="fn", x=3.0000, y=6.0500, w=1.0000, h=1.0000, second="[", alpha="d", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="div", label="/", style="fn", x=4.0000, y=6.0500, w=1.0000, h=1.0000, second="]", alpha="e", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="pipe", label="|", style="fn", x=0.0000, y=7.1000, w=1.0000, h=1.0000, second="deg", alpha="f", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="7", label="7", style="num", x=1.0000, y=7.1000, w=1.0000, h=1.0000, second=nil, alpha="g", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="8", label="8", style="num", x=2.0000, y=7.1000, w=1.0000, h=1.0000, second=nil, alpha="h", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="9", label="9", style="num", x=3.0000, y=7.1000, w=1.0000, h=1.0000, second=nil, alpha="i", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="mul", label="*", style="fn", x=4.0000, y=7.1000, w=1.0000, h=1.0000, second="sqrt", alpha="j", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="ee", label="EE", style="fn", x=0.0000, y=8.1500, w=1.0000, h=1.0000, second="angle", alpha="k", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="4", label="4", style="num", x=1.0000, y=8.1500, w=1.0000, h=1.0000, second=":", alpha="l", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="5", label="5", style="num", x=2.0000, y=8.1500, w=1.0000, h=1.0000, second="MATH", alpha="m", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="6", label="6", style="num", x=3.0000, y=8.1500, w=1.0000, h=1.0000, second="MEM", alpha="n", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="minus", label="-", style="fn", x=4.0000, y=8.1500, w=1.0000, h=1.0000, second="VAR-LINK", alpha="o", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="sto", label="STO", style="fn", x=0.0000, y=9.2000, w=1.0000, h=1.0000, second="RCL", alpha="p", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="1", label="1", style="num", x=1.0000, y=9.2000, w=1.0000, h=1.0000, second="\"", alpha="q", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="2", label="2", style="num", x=2.0000, y=9.2000, w=1.0000, h=1.0000, second=nil, alpha="r", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="3", label="3", style="num", x=3.0000, y=9.2000, w=1.0000, h=1.0000, second=nil, alpha="s", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="plus", label="+", style="fn", x=4.0000, y=9.2000, w=1.0000, h=1.0000, second="CHAR", alpha="u", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="on", label="ON", style="on", x=0.0000, y=10.2500, w=1.0000, h=1.0000, second="OFF", alpha=nil, shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="0", label="0", style="num", x=1.0000, y=10.2500, w=1.0000, h=1.0000, second="<", alpha="v", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="dot", label=".", style="num", x=2.0000, y=10.2500, w=1.0000, h=1.0000, second=">", alpha="w", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="neg", label="(-)", style="num", x=3.0000, y=10.2500, w=1.0000, h=1.0000, second="ANS", alpha="spc", shift=nil, fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
    { id="enter", label="ENTER", style="enter", x=4.0000, y=10.2500, w=1.0000, h=1.0000, second="ENTRY", alpha=nil, shift="~", fkey=nil, kind="key", radius=0.3500, color=nil, label_color=nil, label_size=8, legend_size=6, shape="auto", outline="auto", outline_color=nil, outline_alpha=nil, outline_width=nil, outline_inset=nil, face_glyph="auto" },
  },
}
