#!/usr/bin/env lua
-- Bundle Lua modules into one file via package.preload (keeps require() names).
--
-- Usage:
--   lua tools/bundle.lua -o dist/ti83_cc.lua frontend.computercraft.api
--   lua tools/bundle.lua -o out.lua --root . core.machine
--
-- Options:
--   -o PATH           output file (required)
--   --root DIR        project root for resolving modules (default: repo root)
--   --entry NAME      module returned by the bundle (default: first root)
--   --exclude PREFIX  skip module name / prefix (repeatable)

local ROOT = arg[0]:match("(.+)[/\\]tools[/\\]bundle%.lua$") or "."
package.path = ROOT .. "/?.lua;" .. ROOT .. "/?/init.lua;" .. package.path

local function usage()
  io.stderr:write([[
Usage: lua tools/bundle.lua -o OUT.lua [--root DIR] [--entry MOD] MOD [MOD...]
]])
  os.exit(1)
end

local out_path, root, entry
local excludes = {}
local roots = {}
local i = 1
while i <= #arg do
  local a = arg[i]
  if a == "-o" then
    i = i + 1
    out_path = arg[i]
  elseif a == "--root" then
    i = i + 1
    root = arg[i]
  elseif a == "--entry" then
    i = i + 1
    entry = arg[i]
  elseif a == "--exclude" then
    i = i + 1
    excludes[#excludes + 1] = arg[i]
  elseif a == "-h" or a == "--help" then
    usage()
  elseif a:sub(1, 1) == "-" then
    io.stderr:write("unknown option: " .. a .. "\n")
    usage()
  else
    roots[#roots + 1] = a
  end
  i = i + 1
end

if not out_path or #roots == 0 then
  usage()
end
root = root or ROOT
entry = entry or roots[1]

local function path_for(modname)
  return (root .. "/" .. modname:gsub("%.", "/") .. ".lua"):gsub("\\", "/")
end

local function excluded(modname)
  for _, prefix in ipairs(excludes) do
    if modname == prefix or modname:sub(1, #prefix + 1) == prefix .. "." then
      return true
    end
  end
  return false
end

-- Optional / host-provided modules - never pulled into the bundle.
local EXTERNAL = {
  bit = true,
  bit32 = true,
  ffi = true,
  love = true,
  socket = true,
}

local function strip_comments_for_scan(src)
  -- Drop long comments and line comments so docs/examples are not followed.
  src = src:gsub("%-%-%[%[.-%]%]", "")
  src = src:gsub("%-%-[^\n]*", "")
  return src
end

local function scan_requires(src)
  local found = {}
  src = strip_comments_for_scan(src)
  for name in src:gmatch([[require%s*%(%s*["']([%w_%.%/]+)["']%s*%)]]) do
    local mod = name:gsub("/", ".")
    if not EXTERNAL[mod] and not excluded(mod) then
      found[mod] = true
    end
  end
  return found
end

local order = {}
local seen = {}
local sources = {}

local function add_module(modname)
  if seen[modname] or EXTERNAL[modname] or excluded(modname) then
    return
  end
  seen[modname] = true
  local path = path_for(modname)
  local f, err = io.open(path, "r")
  if not f then
    error("cannot open module " .. modname .. " (" .. path .. "): " .. tostring(err))
  end
  local src = f:read("*a")
  f:close()
  sources[modname] = src
  for dep in pairs(scan_requires(src)) do
    add_module(dep)
  end
  order[#order + 1] = modname
end

for _, r in ipairs(roots) do
  add_module(r)
end
if not seen[entry] then
  add_module(entry)
end

local out = assert(io.open(out_path, "w"))
out:write("-- Auto-generated by tools/bundle.lua - do not edit.\n")
out:write("-- Source tree preserved as package.preload modules.\n")
out:write("-- Entry require: " .. entry .. "\n")
out:write("-- Run this file in ComputerCraft to auto-start; or dofile() and call :run().\n\n")
out:write("local __bundle_args = { ... }\n")
-- ComputerCraft often has no package/require; always install a preload-first shim.
out:write([[
do
  local g = _G or getfenv and getfenv() or nil
  if type(package) ~= "table" then
    package = { preload = {}, loaded = {} }
  end
  if type(package.preload) ~= "table" then package.preload = {} end
  if type(package.loaded) ~= "table" then package.loaded = {} end
  local host_require = require
  local function bundle_require(name)
    if package.loaded[name] ~= nil then
      return package.loaded[name]
    end
    local loader = package.preload[name]
    if type(loader) == "function" then
      local mod = loader(name)
      if mod == nil then mod = true end
      package.loaded[name] = mod
      return mod
    end
    if type(host_require) == "function" then
      return host_require(name)
    end
    error("module '" .. tostring(name) .. "' not found in bundle", 2)
  end
  require = bundle_require
  if type(g) == "table" then
    g.package = package
    g.require = bundle_require
  end
end
local preload = package.preload

]])

for _, modname in ipairs(order) do
  out:write("preload[" .. string.format("%q", modname) .. "] = function(...)\n")
  local src = sources[modname]
  out:write(src)
  if src:sub(-1) ~= "\n" then
    out:write("\n")
  end
  out:write("end\n\n")
end

out:write("local __api = require(" .. string.format("%q", entry) .. ")\n\n")
out:write([[
-- If this file is the shell program (e.g. you ran `ti83_cc` or renamed it to `test`),
-- start the emulator. If another program dofile()'d us, just return the API.
local function __is_main_program()
  if type(shell) ~= "table" or type(shell.getRunningProgram) ~= "function" then
    return false
  end
  local running = shell.getRunningProgram()
  if not running then
    return false
  end
  local run_name = running
  if type(fs) == "table" and fs.getName then
    run_name = fs.getName(running)
  end
  run_name = tostring(run_name):gsub("%.lua$", ""):lower()

  -- Prefer debug.getinfo when present; CC may lack debug.
  local src_name = nil
  if type(debug) == "table" and type(debug.getinfo) == "function" then
    local src = debug.getinfo(1, "S")
    src = src and src.source or ""
    src_name = tostring(src):match("([^/\\]+)$") or tostring(src)
    src_name = src_name:gsub("^@", ""):gsub("%.lua$", ""):lower()
  end
  if not src_name or src_name == "" then
    -- Fallback: treat as main when the running program looks like our bundle.
    return run_name == "ti83_cc" or run_name == "test"
  end
  return src_name == run_name
end

if __is_main_program() then
  print("TI-83 bundle: starting...")
  if type(__api.run) ~= "function" then
    print("ERROR: API missing .run - bundle is corrupt?")
  else
    -- Host parses argv (so --loadapp is never used as a monitor side).
    __api.run({
      args = __bundle_args,
      fps = 30,
    })
  end
end

return __api
]])
out:close()

io.stdout:write(string.format(
  "bundled %d modules -> %s (entry %s)\n",
  #order, out_path, entry
))
